//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramCommunityAssociation
    {
        public int programCommunityAssociationID { get; set; }
        public Nullable<int> serviceID { get; set; }
        public Nullable<int> communityID { get; set; }
    
        public virtual Community Community { get; set; }
        public virtual Service Service { get; set; }
    }
}
