insert into Community values('Panda adoption community','we love pandas');
insert into Contact values('contact1','555-555-5555','exxample@gmail.com');
insert into Department values(1,'Dep1');
insert into Division values(1,'div1');
insert into [Language] values('language 1');
insert into LocationType values('loctype1');
insert into [Location] values(1,'loc1','build1','add1','room1','floor1');
insert into [Program] values('sponsor1','offer1');
insert into [Service] values(1,1,1,'service1','desc1','summ1','area1',1,'employee1','customer1',getdate());
insert into [ServiceCommunityAssociation] values (1,1);
insert into [ServiceLocationAssociation] values (1,1);
insert into [ServiceLanguageAssociation] values (1,1);